openapi: 3.0.0
info:
  title: Bookstore API
  version: 1.0.0
  description: API for managing books in a bookstore

paths:
  /books:
    get:
      summary: Get all books
      responses:
        200:
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBook'
      responses:
        201:
          description: The newly created book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /books/{bookId}:
    get:
      summary: Get a specific book by ID
      parameters:
        - name: bookId
          in: path
          required: true
          description: The ID of the book to retrieve
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: The book with the specified ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        404:
          description: Book not found

    put:
      summary: Update an existing book
      parameters:
        - name: bookId
          in: path
          required: true
          description: The ID of the book to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBook'
      responses:
        200:
          description: The updated book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        404:
          description: Book not found

    delete:
      summary: Delete an existing book
      parameters:
        - name: bookId
          in: path
          required: true
          description: The ID of the book to delete
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: Book deleted successfully
        404:
          description: Book not found

components:
  schemas:
    NeBook:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
        publication_date:
          type: string
          format: date
        isbn:
          type: string
      required:
        - title
        - author
        - publisher
        - publication_date
        - isbn

    NewBook:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
        publication_date:
          type: string
          format: date
        isbn:
          type: string
      required:
        - title
        - author
        - publisher
        - publication_date
        - isbn

    UpdateBook:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
        publication_date:
          type: string
          format: date
